#!/usr/bin/env bash

_fg_completions()
{
  local IFS=$' \t\n'

  if [ "${#COMP_WORDS[@]}" != "2" ]; then
    return
  fi

  # shellcheck disable=SC2207
  COMPREPLY=( $(compgen -o default -W "add \
    cherry \
    flog \
    hash \
    log \
    restore \
    switch \
    unstage" -- "${COMP_WORDS[1]}") )
}

complete -F _fg_completions fuzzygit
