#!/usr/bin/env bash
#   __                           _ _
#  / _|_   _ _________   _  __ _(_) |_
# | |_| | | |_  /_  / | | |/ _` | | __|
# |  _| |_| |/ / / /| |_| | (_| | | |_
# |_|  \__,_/___/___|\__, |\__, |_|\__|
#                    |___/ |___/
#
# fuzzygit - marry git and fzf
#

fg_var_gitPager=$(git config core.pager)

fg_isGitRepo() {
  git rev-parse HEAD > /dev/null 2>&1
}

fg_echo() {
  if [[ "$#" -ne 0 ]]; then
    echo "$@" | xargs -r echo
  fi
}

fg_fzf() {
  # --exact
  fzf --cycle "$@"
}

fg_fzf_single() {
  fzf --cycle +m "$@"
}

fg_switch() {
  fg_isGitRepo || return 1

  # strip the two leading spaces ("* <branch>")
  local sanatize="sed 's/^..//'"
  # get log of branches
  local preview="git log --oneline --graph \$("$sanatize" <<< {})"
  
  # get branches; single selection;
  local item="$(git branch -l | 
    fg_fzf_single --preview="$preview" |
    sh -c "$sanatize")"
  
  # switch to branch if any
  if [[ -n "$item" ]]; then
    local gitout=$(echo "$item" | xargs -I %branch git switch %branch) \
    && fg_echo "$gitout"
  else
    fg_echo "No branches have been found."
  fi
}

bind '"\er": redraw-current-line'
bind '"\C-g\C-b": "$(fg_switch)\n\e\C-e\er"'

# \e\C-e is the default key binding for shell-expand-line. 
#   Using shell-expand-line is not ideal as it expands aliases as well, but it's the easiest way to do it.
# redraw-current-line is required to clear up the prompt when you're not on tmux. 
#   If you're always on tmux, you can omit the part.

  #local git="git status -sz" # s: short; z: NUL instead LF
  #local extract="
  #    sed 's/^.*]  //' |
  #    sed 's/.* -> //' |
  #    sed -e 's/^\\\"//' -e 's/\\\"\$//'"
  #files="$(git)"
  #[[ -n "$files" ]] 

# ---
# --- NOTES 
# ---

# ---
# sed s/^..//
  # s   - search and replace
  # /   - start pattern
  # ^.. - line start and any char two times
  # /   - end pattern
  # /   - no replacement was defined before slash -> remove match

## fg_switch
#echo "$gitout" | xargs -r echo
#echo "$items" | fzf --preview="$preview" --print0 | sh -c "$sanatize" | xargs --null -I %branch git switch %branch >&1 | xargs -r echo
# ---

# ---
## fg_add
# fg_add() {
#   fg_isGitRepo || return 1
#   gitPager=$(git config core.pager)
#   echo $gitPager
#   $(git status -s | fzf -m --cycle --nth 2.. --preview 'git diff --staged -- {-1} | "$gitPager"')
# }
# ---

# ---
  # local sanatizePreview="sed 's/^...//'"                                     # strip the two leading spaces
  # local sanatizeSelection="sed 's/^...//'"
# ---


# ---
  # local added=$(git config --get-color color.status.added green)       # get color codes
  # local changed=$(git config --get-color color.status.changed red)     # get color codes
  # local unmerged=$(git config --get-color color.status.unmerged red)   # get color codes
  # local untracked=$(git config --get-color color.status.untracked red) # get color codes

  # #local items="$(git -c color.status=always status -su |
  #   #grep -F -e "$added" -e "$changed" -e "$unmerged" -e "$untracked" |
  #   #sed -E 's/^(..[^[:space:]]*)[[:space:]]+(.*)$/[\1]  \2/')"
  # # local items="$(git -c color.status=always status -su | 
  # #   sed -E 's/^(..[^[:space:]]*)[[:space:]]+(.*)$/[\1]  \2/' |
  # #   fg_fzf --preview="$preview" --nth 2..,..)"

  # # local items="$(git -c color.status=always -c status.relativePaths=true status -su |
  # #   grep -F -e "$changed" -e "$unmerged" -e "$untracked" |
  # #   sed -E 's/^(..[^[:space:]]*)[[:space:]]+(.*)$/[\1]  \2/'|
  # #   fg_fzf --preview="$preview" --nth 2..,..)"
# ---

# ---
##local gitout=$(echo "$items" | fg_fzf --preview="$preview" --print0 | sh -c "$sanatize" | xargs -t --null -I %filesToAdd git add %filesToAdd) \
##&& fg_echo gitout
#local gitout=$(echo "$items" | fg_fzf --preview="$preview" --nth 2..,.. | xargs -t --null sh -c "$sanatizeSelection" | xargs -t --null -I %filesToAdd git add %filesToAdd) \
#local gitout=$(echo "$items" | fg_fzf --preview="$preview" --nth 2..,.. | xargs -t --null sh -c "$sanatizeSelection" | xargs -t --null -I %filesToAdd echo %filesToAdd) \
#&& fg_echo "$gitout"
# ---